language: node_js
node_js:
- '9'
dist: trusty
sudo: false
cache:
  directories:
  - node_modules
addons:
  ssh-known-hosts:
    secure: "T/X10Epnxs+EUjQTRv+lpiP/tJ4ylEN5iCpZrnU7JSDBitZnAFzFoRNFg46cB3rjO4L9JyPtlogo7fQCBu08sdDeUgFYgg8bAaw/SnxhylKhnd3OL+eLr5HaZSXap4CowydIjAODREMxpyOhj/B9Xn+rliOrehPG8WXQoO1aR0yyXi7PXRCsoOWbUXI9Q/OK77QnMxgYxn+Kqmqm0CBllzqwe1l2PE4X7TjSOX26YVzi7TVCsv6kQ79CveBLmeJSdxCUv7lQfI8k4zn/HJ/5N+Z4x9sUg5bQpPHU0LErnM1tX5eD/XDfWF67J9IYtNIkbh6A+tlL7ELijo3iq7Kf9l/sHQRpI2JpgatvgWKYlHHuvcYRF7n4nmrSLBJh4UKymVZ74wEN8QmhGZfCSqzpJyUbRER7OAtr8YAV6Wc6pcKFoDvlhNwPBxHG23N3ReobZBkpAFRxSSkLAGaVgh4jARhLwMjWA0G+FQABYBrLCFpYyF7AypCTPn/HLab8ZIRPqz55Ws/H6UD+U0DlCNr76UHj1HVsQQjtcnwb/OcEEJhr5Gci6rZbDBv6JaPa9WqLmQyrwBrtmI+GE0IGJlCET7Y3nSubYHnauhyKzgJq0XHs01DbJiHkQoFe92Gvl2zcaUmDKT2SqQEty8BqcTwOR4Er0luIwCEpg3I0LXcztq8="
  apt:
    sources:
    - git-core
    packages:
    - git
before_install:
  - openssl aes-256-cbc -K $encrypted_c3355765ee6c_key -iv $encrypted_c3355765ee6c_iv -in .travis/id_rsa.enc -out .travis/id_rsa -d
  - sudo apt-get update
install: npm install
jobs:
  include:
  - stage: test
    script: bash ./.travis/test.sh
  - stage: deploy
    script: bash ./.travis/deploy.sh
stages:
- test
- name: deploy
  if: branch = production
script: skip

